name: Build for Windows

on:
  push:
    paths-ignore:
      - '.github/**'
      - '!.github/workflows/build.yml'
      - 'README.md'
  pull_request:
    paths-ignore:
      - '.github/**'
      - '!.github/workflows/build.yml'
      - 'README.md'

jobs:
  BuildWindows:
    name: Build for Windows (${{ matrix.arch }}, ${{ matrix.configuration }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - configuration: Release
            build_param: --release
            artifact_name: app-win-x86_64-release
            arch: x86_64
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Pull Docker image
        env:
          DOCKER_IMAGE_NAME: ghcr.io/xemu-project/xemu-win64-toolchain:sha-b6d29d4
        run: docker pull $DOCKER_IMAGE_NAME

      - name: Build executable
        env:
          DOCKER_IMAGE_NAME: ghcr.io/xemu-project/xemu-win64-toolchain:sha-b6d29d4
        run: |
          mkdir -p /tmp/xemu-ccache
          docker run --rm \
            -v $PWD:/xemu -w /xemu \
            -v /tmp/xemu-ccache:/tmp/xemu-ccache \
            -e CCACHE_DIR=/tmp/xemu-ccache \
            -e CCACHE_MAXSIZE=512M \
            -e CROSSPREFIX=${{ matrix.arch }}-w64-mingw32.static- \
            -e CROSSAR=${{ matrix.arch }}-w64-mingw32.static-ar \
            $DOCKER_IMAGE_NAME \
              bash -c "ccache -z; ./build.sh -p win64-cross ${{ matrix.build_param }} && ccache -s"

      - name: Upload .exe artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact_name }}
          path: dist/*.exe
